version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "8080:80"  # Map localhost:8080 to the Nginx container's port 80
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Map localhost:5000 to the backend container's port 5000
    depends_on:
      - database
    networks:
      - app-network

  database:
    build: ./database
    ports:
      - "3306:3306"  # Map localhost:3306 to the MySQL container's port 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
